### ISSUE TITLE
Error after update to 0.8

### ISSUE THREAD

**Issue by grshennan** [Narayana-Rao/PolSAR-tools#12]
Updated the QGIS plugin using the Plugins updater, now this error is produced:

```
Couldn't load plugin 'polsar_tools' due to an error when calling its classFactory() method 

AttributeError: 'NoneType' object has no attribute 'write' 
Traceback (most recent call last):
  File "C:\Users/glens/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\polsar_tools\SAR_Tools.py", line 84, in check_pstools
    import polsartools
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'polsartools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 478, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/glens/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\polsar_tools\__init__.py", line 35, in classFactory
    return PolSAR(iface)
           ^^^^^^^^^^^^^
  File "C:\Users/glens/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\polsar_tools\SAR_Tools.py", line 80, in __init__
    self.check_pstools()
  File "C:\Users/glens/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\polsar_tools\SAR_Tools.py", line 86, in check_pstools
    pip_main(['install', 'polsartools'])
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pip\_internal\__init__.py", line 18, in main
    return _wrapper(args)
           ^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pip\_internal\utils\entrypoints.py", line 35, in _wrapper
    sys.stderr.write(
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'
```

The plugin then doesn't appear in the plugins menu.

Windows 11, QGIS 3.44.1

Python version: 3.12.11 (main, Jun 17 2025, 13:41:12) [MSC v.1943 64 bit (AMD64)] 
QGIS version: 3.44.1-Solothurn Solothurn, c8b94a2061d

Edit: uninstalled and reinstalled plugin, same issue.

**Comment by Narayana-Rao** [comment]
Thanks @grshennan for raising the issue.

The error occurred because we've recently updated the plugin to use the `polsartools` Python package. It seems the automatic installation did not complete successfully. We've now updated the plugin to handle this more reliably.

If you still encounter issues, please follow the manual installation steps below:

## Manual Installation Instructions

1. **Open the Python Console in QGIS**
2. **Run the following commands to install `polsartools`:**
   ```python
   from pip._internal import main as pip_main
   pip_main(['install', 'polsartools'])

Once the above installation is successful, proceed to the installation of the plugin.
